server.port=8082

spring.application.name=api-gateway
eureka.client.service-url.defaultZone = http://localhost:8081/eureka

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**

spring.cloud.gateway.server.webflux.routes[1].id=notification-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/notify/**
